baseURL = "https://gsc4096.github.io"
languageCode = "pt-br"
title = "gsc4096"
theme = "beautifulhugo"

[Params]
homeTitle = "gsc4096"
subtitle = "A brief experiment with a SSG"
mainSections = ["post"]
img = "images/*.png"
favicon = "img/favicon.ico"
dateFormat = "January 2, 2006"
rss = true
readingTime = true
wordCount = true

[Author]
name = "Gabriel"
github = "gsc4096"

[[menu.main]]
name = "Blog"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "page/about/"
weight = 3
